config {
  type: "incremental",
  name: "venues_counts_by_year"
}
Select
json_value(venues,'$.id') as venue_id,
json_value(venues,'$.works_count') as works_count,
json_value(venues,'$.cited_by_count') as cited_by_count ,
json_value(venues,'$.counts_by_year') as year from ${ref("venues")}

-- select *
-- from 
--   ${ref("table_name")} / schema.table_name
-- read more about ref() in the documentation tab -->
